### ISSUE TITLE
link from blog post is broken

### ISSUE THREAD

**Issue by alxndr** [clauswitt/dotfiles#1]
[This blog post](http://www.clauswitt.com/a-walkthrough-of-my-spacemacs-configuration-files.html) links to `https://github.com/clauswitt/dotfiles/tree/master/emacs/spacemacs`, which shows a GitHub error page for me. Could that the link in that blog post be changed to reference a specific SHA which is publicly available?

**Comment by ogrim** [comment]
@alxndr: Have a look at b56e5ab06b704

**Comment by alxndr** [comment]
> the posts I wrote were absolutely without any value

...this is not true; I found value in your post about Spacemacs @clauswitt.
